spring:
  datasource:
    url: jdbc:h2:file:/root/test/H2testdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
        trace: true #允许远程web访问